apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-tracker
  labels:
    app: price-tracker
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: price-tracker
  template:
    metadata:
      labels:
        app: price-tracker
    spec:
      containers:
      - name: price-tracker
        image: myrepo/price-tracker:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"