name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Using a single, stable version
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov black isort
        pip install -e .
        pip install -r requirements.txt
    
    - name: Run tests with pytest
      run: |
        python -m pytest tests/ --cov=src --cov-report=xml -v

    - name: Run unit tests
      run: |
        pytest tests/ --cov=src --cov-report=term-missing
    
    - name: Run integration tests
      run: |
        pytest integration_tests/
    
    - name: Run security scans
      uses: SonarSource/sonarcloud-github-action@v1.5
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=my_project_key
          -Dsonar.organization=my_organization
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}